### PR TITLE
Fix word wise for stressed Russian epubs

### PR DESCRIPTION
**Pull request by Vuizur**
I fixed the code for stressed epubs by using (only in this special case) two spacy docs: one containing the text and one for the lemmatization/pos detection. I tested it for one Russian and one non-Russian book so far and it seemed to work.
Should I add the same for kindle? (I only can't test it.)

### CODE REVIEW

**Comment by xxyzz** [comment]
Only one character need to be removed? It could be added at here: https://github.com/xxyzz/WordDumb/blob/460db47886fc1f6fe36e2329c659b3ee54a837a5/epub.py#L137-L144

**Comment by Vuizur** [comment]
Removing that one character works fine for books created by my program, for general purpose one should maybe use the more sophisticated remove_accents function like in Proficiency, which can also remove grave accents. 

I don't 100 percent understand the code, but removing it from the place you suggested will also remove the character from the output epub, right? I would want to keep it.

**Comment by xxyzz** [comment]
Yes, that'll change the book text, I forget you want to keep the stress marker...

This issue should be fixed in spaCy's Russian lemmatizer, change the text using `str.replace` breaks the word location and would make the footnote added to the wrong place.

**Comment by Vuizur** [comment]
There is an issue on the spacy repo that is related to the fixing of the lemmatizer: https://github.com/explosion/spaCy/issues/12530. It seems terribly complicated. 
I think my workaround works fine. It takes the token index positions, because these don't change between stressed and unstressed texts, so the alignment is kept.

**Comment by xxyzz** [comment]
I think it's better to wait for spaCy's pr, sorry. This patch runs the model pipelines on words that have stress marks again...

**Comment by Vuizur** [comment]
On Russian words with stress marks. So it doesn't affect any non-Russian books, and no normal Russian books. It probably won't even affect normal Russian books that have French citations like "À mauvais ouvrier point de bon outil.", because it only detects combining accent marks. So the performance impact should be negligible in all other cases except with stressed Russian books, where the program is currently broken.

The problem with the spacy PR is that the original one has been sitting for almost a year, and only fixes lemmatisation, but not POS detection. For fixing POS detection we would apparently have to host our own `unstressed_core_news_*` models and implement a custom language, which would probably result in more convoluted code changes than in this PR.

**Comment by xxyzz** [comment]
Doesn't the English Wiktionary have forms that have stress marks? Have you tried disable the "Use POS type" feature, stressed forms should be matched if they are in the Word Wise db.

**Comment by Vuizur** [comment]
> Doesn't the English Wiktionary have forms that have stress marks? Have you tried disable the "Use POS type" feature, stressed forms should be matched if they are in the Word Wise db.

True, this works.

**Comment by xxyzz** [comment]
Another way to fix this is add word wise notes first then add stress marks...

**Comment by Vuizur** [comment]
> Another way to fix this is add word wise notes first then add stress marks...
It is possible, although implementing that would be hard. 🗿

**Comment by xxyzz** [comment]
I think this is fixed in the latest release, all enabled forms can be matched.

**Comment by Vuizur** [comment]
I think it should be, thanks!

Dne pá 9. 8. 2024 16:11 uživatel xxyzz ***@***.***> napsal:

**Pull request closed without merging**
